version: '3.8'

services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DISPLAY=:99 

  redis:
    image: redis:7.0
    platform: linux/amd64
    container_name: redis_server
    ports:
      - "6379:6379"
