name: myenv
channels:
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/main/
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  # 删除 Windows-only 包（如 vc、vs2015_runtime），只保留跨平台和 Linux 可用包
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.15
  - python=3.11.11
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip
  - pip:
      - absl-py
      - acres
      - alabaster
      - annotated-types
      - anyio
      - appdirs
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asgiref
      - asttokens
      - async-lru
      - attrs
      - autobahn
      - automat
      - babel
      - backcall
      - beautifulsoup4
      - bleach
      - certifi
      - cffi
      - channels
      - channels-redis
      - chardet
      - charset-normalizer
      - ci-info
      - click
      - colorama
      - comm
      - configobj
      - configparser
      - constantly
      - contourpy
      - cryptography
      - cycler
      - cython
      - daphne
      - debugpy
      - decorator
      - defusedxml
      - distro
      - django
      - django-bootstrap4
      - docopt
      - docutils
      - easyocr
      - et-xmlfile
      - etelemetry
      - executing
      - fastjsonschema
      - filelock
      - fitz
      - fonttools
      - fqdn
      - fsspec
      - future
      - greenlet
      - grpcio
      - h11
      - httpcore
      - httplib2
      - httpx
      - hyperlink
      - idna
      - imageio
      - imagesize
      - imgkit
      - importlib-metadata
      - importlib-resources
      - incremental
      - ipykernel
      - ipython
      - ipywidgets
      - isodate
      - isoduration
      - itk
      - itk-core
      - itk-filtering
      - itk-io
      - itk-numerics
      - itk-registration
      - itk-segmentation
      - jedi
      - jinja2
      - jiter
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - kiwisolver
      - lazy-loader
      - looseversion
      - lxml
      - markdown
      - markupsafe
      - matplotlib
      - matplotlib-inline
      # - mermaid
      - mistune
      - mouseinfo
      - mpmath
      - msgpack
      - mysqlclient
      - narwhals
      - nbclient
      - nbconvert
      - nbformat
      - nbsphinx
      - nest-asyncio
      - networkx
      - nibabel
      - ninja
      - nipype
      - notebook
      - notebook-shim
      - numpy
      - openai
      - opencv-python-headless
      - openpyxl
      - overrides
      - packaging
      - pandas
      - pandoc
      - pandocfilters
      - parso
      - pathlib
      - patsy
      - pdf2image
      - pickleshare
      - pillow
      - pip
      - pipreqs
      - platformdirs
      - playwright
      - plotly
      - plumbum
      - ply
      - progressbar2
      - prometheus-client
      - prompt-toolkit
      - protobuf
      - prov
      - psutil
      - pure-eval
      - puremagic
      - pyasn1
      - pyasn1-modules
      - pyautogui
      - pyclipper
      - pycparser
      - pydantic
      - pydantic-core
      - pydot
      - pyee
      - pygetwindow
      - pygments
      - pymsgbox
      - pymupdf
      - pynput
      - pynrrd
      - pyopenssl
      - pypandoc
      - pyparsing
      - pyperclip
      - pyppeteer
      - pyqt5
      - pyqt5-qt5
      - pyqt5-sip
      - pyrect
      - pyscreeze
      - pytesseract
      - python-bidi
      - python-dateutil
      - python-json-logger
      - python-utils
      - pytweening
      # - pytz
      # - pywin32
      # - pywinpty
      - pyxnat
      - pyyaml
      - pyzmq
      - rdflib
      - redis
      - referencing
      - reportlab
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - rpds-py
      - scikit-image
      - scipy
      - send2trash
      - service-identity
      - shapely
      - simplejson
      - six
      - sniffio
      - snowballstemmer
      - soupsieve
      - sphinx
      - sphinx-gallery
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - sqlparse
      - stack-data
      - statsmodels
      - sympy
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - termcolor
      - terminado
      - tifffile
      - tinycss2
      - torch
      - torchvision
      - tornado
      - tqdm
      - traitlets
      - traits
      - twisted
      - txaio
      - types-python-dateutil
      - typing-extensions
      - tzdata
      - uri-template
      - urllib3
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - websockets
      - werkzeug
      - widgetsnbextension
      - wkhtmltopdf
      - yarg
      - zipp
      - zope-interface
