# Generated by Django 4.2.20 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='group_id',
            field=models.CharField(max_length=100),
        ),
    ]
