# Generated by Django 5.1.6 on 2025-05-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button_lock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
