# Generated by Django 5.1.6 on 2025-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('button_lock', '0002_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_user', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
