# Generated by Django 5.1.6 on 2025-05-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("button_lock", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="code",
            field=models.TextField(default='# 初始代码\nprint("Hello World")'),
        ),
    ]
