# Generated by Django 5.1.6 on 2025-04-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_id', '0006_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_rooms', to='group_id.roomfile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
