# Generated by Django 4.2.20 on 2025-05-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDE', '0002_course_created_at_course_last_updated'),
        ('lesson', '0002_chatroom_current_pdf_chatroom_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='IDE.course'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('name', 'course')},
        ),
    ]
