# Generated by Django 4.2.2 on 2025-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_buttonstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonstate',
            name='last_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
