# Generated by Django 4.2.2 on 2025-04-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_id', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS group_id_roomfile;",
        ),
    ]
