# Generated by Django 4.2.2 on 2025-04-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_id', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomfile',
            name='file',
        ),
        migrations.AddField(
            model_name='roomfile',
            name='file_data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='roomfile',
            name='file_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
