# Generated by Django 4.2.2 on 2025-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_id', '0004_remove_roomfile_file_roomfile_file_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomFile',
        ),
    ]
